### ISSUE TITLE
Add Orca findings

### ISSUE THREAD

**Issue by 0xdabbad00** [SummitRoute/csp_security_mistakes#26]
https://orca.security/resources/blog/aws-glue-vulnerability/
https://orca.security/resources/blog/aws-cloudformation-vulnerability/

**Comment by 0xdabbad00** [comment]
They are calling them Superglue & BreakingFormation.

https://twitter.com/orcasec/status/1481653705283756043

**Comment by mwarkentin** [comment]
AWS has posted their notifications:

https://aws.amazon.com/security/security-bulletins/AWS-2022-002/

https://aws.amazon.com/security/security-bulletins/AWS-2022-001/

**Comment by 0xdabbad00** [comment]
Added in https://github.com/SummitRoute/csp_security_mistakes/commit/7a2a8d1d2c9495b395687c69e092b67e1f4c68d0
